- importar o selenium
- importante: baixar o webdriver

In [29]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\yure\anaconda3\lib\site-packages (4.7.2)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\yure\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: trio~=0.17 in c:\users\yure\anaconda3\lib\site-packages (from selenium) (0.22.0)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\yure\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\users\yure\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\yure\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: sortedcontainers in c:\users\yure\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\yure\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: outcome in c:\users\yure\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in c:\users\yure\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: async-generator>=1.9 in c:\users\yure\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: sniffio in c:\users\yure\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: cffi>=1.14 in c:\users\yure\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\yure\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\yure\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\yure\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\yure\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [30]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

navegador = webdriver.Chrome() # abrir o navegador

navegador.get("https://www.google.com/") # entrar no google


# cotação do Dólar
navegador.find_element('xpath', '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("cotação dólar") # encontrar xpath e escrever texto de busca
navegador.find_element('xpath', '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER) # clicar ENTER

cotacao_dolar = navegador.find_element('xpath', '//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute('data-value') # pegar a cotação do dolar

print(cotacao_dolar)


# cotação do Euro
navegador.get("https://www.google.com/")

navegador.find_element('xpath','/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("cotação euro")
navegador.find_element('xpath','/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)

cotacao_euro = navegador.find_element('xpath','//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute("data-value")
print(cotacao_euro)


# cotação do Ouro
navegador.get("https://www.melhorcambio.com/ouro-hoje") # Entrar no site que contém o valor do Ouro

cotacao_ouro = navegador.find_element('xpath', '//*[@id="comercial"]').get_attribute("value")
cotacao_ouro = cotacao_ouro.replace(",", ".")

print(cotacao_ouro)

navegador.quit()

5.086412999999999
5.5085999999999995
314.49

- importar o pandas

In [31]:
# Importar a lista de produtos
import pandas as pd

tabela = pd.read_excel("Produtos.xlsx")
display(tabela)

,Produtos,Preço Original,Moeda,Cotação,Preço de Compra,Margem,Preço de Venda
0,Câmera Canon,999.99,Dólar,5,4999.95,1.40,6999.930
1,Carro Renault,4500.00,Euro,6,27000.00,2.00,54000.000
2,Notebook Dell,899.99,Dólar,5,4499.95,1.70,7649.915
3,IPhone,799.00,Dólar,5,3995.00,1.70,6791.500
4,Carro Fiat,3000.00,Euro,6,18000.00,1.90,34200.000
5,Celular Xiaomi,480.48,Dólar,5,2402.40,2.00,4804.800
6,Joia 20g,20.00,Ouro,350,7000.00,1.15,8050.000

In [32]:
# Recalcular o preço de cada produto 

# atualizar cotação
tabela.loc[tabela["Moeda"] == "Dólar", "Cotação"] = float(cotacao_dolar)
tabela.loc[tabela["Moeda"] == "Euro", "Cotação"] = float(cotacao_euro)
tabela.loc[tabela["Moeda"] == "Ouro", "Cotação"] = float(cotacao_ouro)

# atualizar o preço base reais
tabela["Preço de Compra"] = tabela["Cotação"] * tabela["Preço Original"]

# atuaçizar o preço final
tabela["Preço de Venda"] = tabela["Preço de Compra"] * tabela["Margem"]

display(tabela)

,Produtos,Preço Original,Moeda,Cotação,Preço de Compra,Margem,Preço de Venda
0,Câmera Canon,999.99,Dólar,5.086413,5086.362136,1.40,7120.906990
1,Carro Renault,4500.00,Euro,5.508600,24788.700000,2.00,49577.400000
2,Notebook Dell,899.99,Dólar,5.086413,4577.720836,1.70,7782.125421
3,IPhone,799.00,Dólar,5.086413,4064.043987,1.70,6908.874778
4,Carro Fiat,3000.00,Euro,5.508600,16525.800000,1.90,31399.020000
5,Celular Xiaomi,480.48,Dólar,5.086413,2443.919718,2.00,4887.839436
6,Joia 20g,20.00,Ouro,314.490000,6289.800000,1.15,7233.270000

In [33]:
# Salvar os novos preços dos produtos

tabela.to_excel("Produtos Novo.xlsx", index=False)